import { useEffect, useMemo, useState } from "react";

const API = import.meta.env.VITE_API_URL || "/api";
export default function Government({token}:{token:string}){
 const [data,setData]=useState<any>(null); const [challenges,setChallenges]=useState<any[]>([]); const [orgs,setOrgs]=useState<any[]>([]); const [tab,setTab]=useState<'overview'|'challenges'|'organizations'>('overview'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const h={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
 async function load(){try{const [a,b,c]=await Promise.all([fetch(`${API}/government/dashboard`,{headers:h}),fetch(`${API}/government/challenges`,{headers:h}),fetch(`${API}/government/organizations`,{headers:h})]); const [ad,bd,cd]=await Promise.all([a.json(),b.json(),c.json()]); if(!a.ok)throw new Error(ad.error); setData(ad);setChallenges(bd.challenges||[]);setOrgs(cd.organizations||[])}catch(e){setError(e instanceof Error?e.message:'Could not load government dashboard')}}
 useEffect(()=>{load()},[]);
 async function moderate(id:string,status:string){setBusy(true);try{await fetch(`${API}/government/challenges/${id}/moderation`,{method:'PATCH',headers:h,body:JSON.stringify({status,reason:status==='HIDDEN'?'Hidden by government moderation':''})});await load()}finally{setBusy(false)}}
 async function verify(id:string,verified:boolean){setBusy(true);try{await fetch(`${API}/government/organizations/${id}`,{method:'PATCH',headers:h,body:JSON.stringify({verified})});await load()}finally{setBusy(false)}}
 const maxDistrict=Math.max(1,...(data?.districts||[]).map((x:any)=>x.challenges));
 const maxCat=Math.max(1,...(data?.categories||[]).map((x:any)=>x.challenges));
 if(error)return <section className="list-section"><div className="error">{error}</div></section>;
 if(!data)return <section className="list-section"><div className="ai-loading">Loading government command center…</div></section>;
 return <section className="list-section government-page"><div className="section-head"><div><p className="eyebrow">PHASE 10 • GOVERNMENT PLATFORM</p><h2>Jharkhand Innovation Command Center</h2><p className="section-subtitle">Monitor societal challenges, institutional delivery, verified partners and measurable community impact.</p></div><div className="gov-tabs">{(['overview','challenges','organizations'] as const).map(x=><button key={x} className={tab===x?'selected':''} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div></div>
 <div className="stat-grid gov-kpis">{[['Challenges',data.kpis.total_challenges],['Resolved',data.kpis.resolved_challenges],['Projects',data.kpis.total_projects],['Completed',data.kpis.completed_projects],['Verified partners',data.kpis.verified_organizations],['Urgent open',data.kpis.urgent_open]].map(([k,v])=><div key={String(k)}><b>{k}</b><strong>{v}</strong><span>Live platform measure</span></div>)}</div>
 {tab==='overview'&&<><div className="gov-grid"><article className="gov-card"><h3>Jharkhand activity map</h3><div className="jh-map"><div className="jh-outline"/>{challenges.filter((x:any)=>x.latitude!=null&&x.longitude!=null).slice(0,80).map((x:any)=><span key={x.id} title={x.title} style={{left:`${Math.max(4,Math.min(94,((x.longitude-83.3)/3.3)*100))}%`,top:`${Math.max(5,Math.min(94,((25.4-x.latitude)/3.3)*100))}%`}}/>)}<small>Reported challenge locations · live coordinates</small></div></article><article className="gov-card"><h3>District challenge load</h3>{data.districts.map((d:any)=><div className="bar-row" key={d.district}><span>{d.district}</span><div><i style={{width:`${Math.round(d.challenges/maxDistrict*100)}%`}}/></div><b>{d.challenges}</b></div>)}</article><article className="gov-card"><h3>Category demand</h3>{data.categories.map((d:any)=><div className="bar-row" key={d.category}><span>{d.category}</span><div><i style={{width:`${Math.round(d.challenges/maxCat*100)}%`}}/></div><b>{d.challenges}</b></div>)}</article></div><div className="gov-grid"><article className="gov-card"><h3>Impact ledger</h3><div className="impact-grid"><div><b>{data.impact.people_affected}</b><span>People affected</span></div><div><b>{data.impact.villages_affected}</b><span>Villages affected</span></div><div><b>{data.impact.time_saved_hours}</b><span>Hours saved</span></div></div></article><article className="gov-card"><h3>Urgent / high priority</h3>{data.urgent.length===0?<p className="muted">No open urgent challenges.</p>:data.urgent.slice(0,6).map((x:any)=><div className="compact-row" key={x.id}><strong>{x.title}</strong><span>{x.district||'District not supplied'} · {x.urgency_hint}</span></div>)}</article></div></>}
 {tab==='challenges'&&<div className="challenge-list">{challenges.map(c=><article className="challenge" key={c.id}><div className="challenge-top"><span className="tag">{c.status}</span><span className="meta">{c.district||'Location not supplied'} · {c.category||'Uncategorized'}</span></div><h3>{c.title}</h3><p>{c.description}</p><small>{c.citizen_name} · {c.request_type} · {c.urgency_hint}</small><div className="two"><button className="secondary-btn" disabled={busy} onClick={()=>moderate(c.id,'HIDDEN')}>Hide</button><button className="secondary-btn" disabled={busy} onClick={()=>moderate(c.id,'VISIBLE')}>Restore</button></div></article>)}</div>}
 {tab==='organizations'&&<div className="challenge-list">{orgs.map(o=><article className="challenge" key={o.id}><div className="challenge-top"><span className="tag">{o.verified?'VERIFIED':'UNVERIFIED'}</span><span className="meta">{o.organization_type} · {o.district||'District not supplied'}</span></div><h3>{o.name}</h3><p>{o.description||'No organization description.'}</p><div className="impact-grid"><div><b>{o.average_rating}</b><span>Rating</span></div><div><b>{o.rating_count}</b><span>Trusted reviews</span></div><div><b>{o.member_count}</b><span>Members</span></div></div><button className="secondary-btn" disabled={busy} onClick={()=>verify(o.id,!o.verified)}>{o.verified?'Revoke verification':'Verify organization'}</button></article>)}</div>}
 </section>
}
